-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 16:11:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema test_user_DB_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_user_DB_1` ;

-- -----------------------------------------------------
-- Schema test_user_DB_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_user_DB_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema test_user_DB
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usergroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usergroup` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usergroup` (
  `user_id` INT NOT NULL,
  `groupname` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`board` ;

CREATE TABLE IF NOT EXISTS `mydb`.`board` (
  `board_id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `author` INT NOT NULL,
  `createdate` DATETIME NOT NULL,
  `modifiedate` DATETIME NOT NULL,
  PRIMARY KEY (`board_id`),
  INDEX `author_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `test_user_DB_1` ;

-- -----------------------------------------------------
-- Table `test_user_DB_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_user_DB_1`.`users` ;

CREATE TABLE IF NOT EXISTS `test_user_DB_1`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_user_DB_1`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_user_DB_1`.`board` ;

CREATE TABLE IF NOT EXISTS `test_user_DB_1`.`board` (
  `board_id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `author` INT NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`board_id`),
  INDEX `author` (`author` ASC) VISIBLE,
  CONSTRAINT `board_ibfk_1`
    FOREIGN KEY (`author`)
    REFERENCES `test_user_DB_1`.`users` (`user_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_user_DB_1`.`usergroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_user_DB_1`.`usergroup` ;

CREATE TABLE IF NOT EXISTS `test_user_DB_1`.`usergroup` (
  `user_id` INT NULL DEFAULT NULL,
  `groupname` VARCHAR(50) NOT NULL,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `usergroup_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test_user_DB_1`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
